name: Windows Build

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: |
            git
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-make

      - name: Checkout Master
        uses: actions/checkout@v3
        with:
          ref: master
          submodules: recursive

      - name: Make Envs
        shell: msys2 {0}
        run: |
          pacman -S --noconfirm --needed --quiet --noprogressbar git mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-make
          cp /ucrt64/bin/mingw32-make /ucrt64/bin/make
          make envs

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            build-mingw64
          key: ${{ runner.os }}-${{ hashFiles('Makefile') }}

      - name: Build
        shell: msys2 {0}
        run: |
          make
          ldd main

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: build
