name: Ubuntu Build

on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v4
        with:
          ref: master
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -y git build-essential g++
          sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-gfx-dev libsdl2-net-dev zlib1g-dev libzip-dev libyaml-dev bison libffi-dev libgmp-dev upx p7zip-full vim unzip


      - name: Make Envs
        run: |
          make envs

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ./packages/download
            ./download
          key: ${{ hashFiles('Makefile') }}

      - name: Download Miscs
        run: |
          wget -q http://7niu.gxmatmars.com/p1/RGModern/misc.7z
          make misc

      - name: Build
        run: |
          make
          ldd main

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: rgm-ubuntu
          path: |
            *
